export const BetParam = {
    1: 1, // [{ Title: '特碼' }],
    2: 1, // [{ Title: '特碼單雙'}],
    3: 1, // [{ Title: '特碼大小'}],
    74: 1, // [{ Title: '特碼尾大小'}],
    4: 1,  // [{ Title: '正碼' }],
    5: 1,  // [{ Title: '總和單雙'}],
    6: 1,  // [{ Title: '總和大小'}],
    7: 3,  // [{ Title: '三全中' }],
    8: 3,  // [{ Title: '三中二 I',SubTitle:'中二'},{ Title: '三中二 I',SubTitle:'全中',Filter:'>100'}],
    72: 3, // [{ Title: '三中二 II',SubTitle:'中二'},{ Title: '三中二 II',SubTitle:'全中',Filter:'>100'}],
    9: 2,  // [{ Title: '二全中' }],
    10: 2, // [{ Title: '二中特 I',SubTitle:'中特'},{ Title: '二中特 I',SubTitle:'中二',Filter:'>100'}],
    73: 2, // [{ Title: '二中特 II',SubTitle:'中特'},{ Title: '二中特 II',SubTitle:'中二',Filter:'>100'}],
    11: 2, // [{ Title: '特串' }],
    71: 4, // [{ Title: '四中一' }],
    12: 1, // [{ Title: '正碼1-6單雙'}],
    13: 1, // [{ Title: '正碼1-6大小'}],
    14: 1, // [{ Title: '正碼1-6色波',SubTitle: '藍綠波'},{ Title: '正碼1-6色波',SubTitle: '紅波'}],
    27: 1, // [{ Title: '正1-6合數單雙'}],
    15: 0, // [{ Title: "正碼過關"}],
    16: 1, // [{ Title: '特碼合數單雙'}],
    17: 1, // [{ Title: '特碼色波',SubTitle: '藍綠波' },{ Title: '特碼色波',SubTitle: '紅波' }],
    18: 1, // [{ Title: '特碼生肖',SubTitle:'一般'},{ Title: '特碼生肖',SubTitle:'1號生肖'}],
    19: 1, // [{ Title: '生肖',SubTitle: '一般'},{ Title: '生肖',SubTitle:'1號生肖'}],
    20: 1, // [{ Title: '尾數',SubTitle: '一般'},{ Title: '尾數',SubTitle:'0尾'}],
    21: 1, // [{ Title: '正1特' }],
    22: 1, // [{ Title: '正2特' }],
    23: 1, // [{ Title: '正3特' }],
    24: 1, // [{ Title: '正4特' }],
    25: 1, // [{ Title: '正5特' }],
    26: 1, // [{ Title: '正6特' }],
    29: 1, /*[{ Title: '半波',SubTitle:'紅單'},
          { Title: '半波',SubTitle:'紅雙'},
          { Title: '半波',SubTitle:'紅大'},
          { Title: '半波',SubTitle:'紅小'},
          { Title: '半波',SubTitle:'藍單'},
          { Title: '半波',SubTitle:'藍雙'},
          { Title: '半波',SubTitle:'藍大'},
          { Title: '半波',SubTitle:'藍小'},
          { Title: '半波',SubTitle:'綠單'},
          { Title: '半波',SubTitle:'綠雙'},
          { Title: '半波',SubTitle:'綠大'},
          { Title: '半波',SubTitle:'綠小'}],*/
    75: 2, // [{ Title: '二肖'}],
    76: 3, // [{ Title: '三肖'}],
    77: 4, // [{ Title: '四肖'}],
    78: 5, // [{ Title: '五肖'}],
    30: 6, // [{ Title: '六肖'}],
    31: 5, // [{ Title: '五不中'}],
    48: 6, // [{ Title: '六不中'}],
    49: 7, // [{ Title: '七不中'}],
    50: 8, // [{ Title: '八不中'}],
    51: 9, // [{ Title: '九不中'}],
    52: 10, // [{ Title: '十不中'}],
    32: 2, // [{ Title: '二肖連-中', SubTitle:'一般'},{ Title: '二肖連-中', SubTitle:'1號生肖'}],
    33: 3, // [{ Title: '三肖連-中', SubTitle:'一般'},{ Title: '三肖連-中', SubTitle:'1號生肖'}],
    34: 4, // [{ Title: '四肖連-中', SubTitle:'一般'},{ Title: '四肖連-中', SubTitle:'1號生肖'}],
    44: 5, // [{ Title: '五肖連-中', SubTitle:'一般'},{ Title: '五肖連-中', SubTitle:'1號生肖'}],
    35: 2, // [{ Title: '二肖連-不中', SubTitle:'一般'},{ Title: '二肖連-不中', SubTitle:'1號生肖'}],
    36: 3, // [{ Title: '三肖連-不中', SubTitle:'一般'},{ Title: '三肖連-不中', SubTitle:'1號生肖'}],
    37: 4, // [{ Title: '四肖連-不中', SubTitle:'一般'},{ Title: '四肖連-不中', SubTitle:'1號生肖'}],
    45: 5, // [{ Title: '五肖連-不中', SubTitle:'一般'},{ Title: '五肖連-不中', SubTitle:'1號生肖'}],
    38: 2, // [{ Title: '二尾連-中', SubTitle:'一般'},{ Title: '二尾連-中', SubTitle:'0尾'}],
    39: 3, // [{ Title: '三尾連-中', SubTitle:'一般'},{ Title: '三尾連-中', SubTitle:'0尾'}],
    40: 4, // [{ Title: '四尾連-中', SubTitle:'一般'},{ Title: '四尾連-中', SubTitle:'0尾'}],
    46: 5, // [{ Title: '五尾連-中', SubTitle:'一般'},{ Title: '五尾連-中', SubTitle:'0尾'}],
    41: 2, // [{ Title: '二尾連-不中', SubTitle:'一般'},{ Title: '二尾連-不中', SubTitle:'0尾'}],
    42: 3, // [{ Title: '三尾連-不中', SubTitle:'一般'},{ Title: '三尾連-不中', SubTitle:'0尾'}],
    43: 4, // [{ Title: '四尾連-不中', SubTitle:'一般'},{ Title: '三尾連-不中', SubTitle:'0尾'}],
    47: 5, // [{ Title: '五尾連-不中', SubTitle:'一般'},{ Title: '五尾連-不中', SubTitle:'0尾'}],
    53: 1, /*[{ Title: '七碼', SubTitle: '單0大0'},
          { Title: '七碼', SubTitle: '單1大1'},
          { Title: '七碼', SubTitle: '單2大2'},
          { Title: '七碼', SubTitle: '單3大3'},
          { Title: '七碼', SubTitle: '單4大4'},
          { Title: '七碼', SubTitle: '單5大5'},
          { Title: '七碼', SubTitle: '單6大6'},
          { Title: '七碼', SubTitle: '單7大7'}],*/
    54: 1, // [{ Title: '五行',SubTitle:'一般'},{ Title: '五行',SubTitle:'土'}],
    55: 1, /*[{ Title: '一肖量',SubTitle: '肖2'},
          { Title: '一肖量',SubTitle: '肖3'},
          { Title: '一肖量',SubTitle: '肖4'},
          { Title: '一肖量',SubTitle: '肖5'},
          { Title: '一肖量',SubTitle: '肖6'},
          { Title: '一肖量',SubTitle: '肖7'}],*/
    56: 1, /*[{Title: '尾數量', SubTitle: '尾2'},
          {Title: '尾數量', SubTitle: '尾3'},
          {Title: '尾數量', SubTitle: '尾4'},
          {Title: '尾數量', SubTitle: '尾5'},
          {Title: '尾數量', SubTitle: '尾6'},
          {Title: '尾數量', SubTitle: '尾7'}],*/
    57: 5, // [{ Title: '五中一' }],
    58: 6, // [{ Title: '六中一' }],
    59: 7, // [{ Title: '七中一' }],
    60: 8, // [{ Title: '八中一' }],
    61: 9, // [{ Title: '九中一' }],
    62: 10, // [{ Title: '十中一' }],
    63: 1, // [{ Title: '一粒任中' }],
    64: 2, // [{ Title: '二粒任中' }],
    65: 3, // [{ Title: '三粒任中' }],
    66: 4, // [{ Title: '四粒任中' }],
    67: 5, // [{ Title: '五粒任中' }],
    68: 1, // [{ Title: '龍虎'}],
    69: 1, // [{ Title: '一肖不中',SubTitle: '一般'},{ Title: '一肖不中',SubTitle:'1號生肖'}],
    70: 1, // [{ Title: '尾數不中',SubTitle: '一般'},{ Title: '尾數不中',SubTitle:'0尾'}]
    };
